# Introduction to Python 

This tutorial is heavily based on [this tutorial on audio signal processing](https://github.com/spatialaudio/selected-topics-in-audio-signal-processing-exercises).

For most of the exercises, we will use the very popular programming language [Python](https://www.python.org) together with a few external libraries from the [Scientific Python Stack](http://scipy.org).
To get started, you might also want to have a look a those:

* [Python Introduction](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/intro-python.ipynb) (pure Python, no NumPy)

* [Simple Signal Processing Example](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/simple-signals.ipynb) (quite similar to the things on this very page)

Note that Python is not the only option for the kind of tasks that we'll tackle here.
If you are interested in some alternatives, have a look at [Julia](http://julialang.org/), [R](http://www.r-project.org/), [Octave](http://octave.org/) or [Scilab](http://www.scilab.org/).
All the mentioned applications are open-source software and there are of course even more alternatives (both free and proprietary).

Most of the exercises in this course (including the one you're reading right now) are presented as [Jupyter (formerly known as IPython) notebooks](http://jupyter.org/).
They can be [viewed online](http://nbviewer.jupyter.org/github/spatialaudio/communication-acoustics-exercises/blob/master/index.ipynb), but it makes much more sense to download them and open and explore them locally with [Jupyter](http://jupyter.org/).

For installation instructions, see the section [Getting Started](index.ipynb#Getting-Started) on the main page.

To get an idea what Jupyter is all about, have a look at this [Jupyter Introduction](http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/intro-jupyter.ipynb).


## What Will We Learn Today?

* Basics of Python, Jupyter/IPython, NumPy, SciPy, matplotlib and some other external libraries


## Notebook Cells

This notebook consists of so-called "cells", which can be used for normal text (see above) or for Python code (see below).
*Code cells* can be selected by a mouse click (or with the arrow up/down keys and *Enter*), the code can be edited and then executed by pressing *Shift+Enter* or by clicking the <button class="fa fa-step-forward fa-play icon-play btn btn-xs btn-default"></button> button in the top part of the page.

Don't be shy, try it:

In [1]:
50 - 5 * 4 + 12

42

Code cells can have multiple lines (use *Enter* for line breaks).
When the code cell is executed, all lines are executed, but only the value of the last line is displayed (except if there is no value to display).

Here's another code cell for you to play with:

In [2]:
print("foo")

foo


New cells can be inserted by pressing the *a* or *b* keys (to insert *above* or *below* the current cell) or via the menu. You should also have a look at "Help" -> "Keyboard Shortcuts".

You can step through all cells in the notebook by repeatedly pressing *Shift+Enter*.
Alternatively, you can click "Run All" in the "Cell" menu.

# Basics
Below is a Python program containing a lot of the operations you will typically need: Assignments, arithmetics, logical operators, printing, comments. As you see, Python is quite easy to read, I am sure you can figure out the meaning of each line yourself.

In [3]:
x = 34 - 23 # A comment.
y = "Hello" # Another one.
z = 3.45
if z == 3.45 or y == "Hello":
    x = x + 1
    y = y + " World"
print(x)
print(y)

12
Hello World


## Indentation
Python handles blocks in a different way than other programming languages you might know, like Java or C: The first line with less indentation is outside of the block, the first line with more indentation starts a nested block. A colon often starts a new block. For example, in the code below, the fourth line is always executed, because it is not part of the block:

In [ ]:
if 17<16:
    print("executed conditionally")
    print("also conditionally")
print("always executed, because not part of the block above")

## Reference Semantics
Assignments behave as you might know from Java: For atomic data types, assignments work "by value", for all other data types (e.g. lists), assignments work "by reference": If we manipulate an object, this influences all references.

In [ ]:
a=17
b=a #assign the *value* of a to b
a=12
print(b) #still 12, because assinment by value

x=[1,2,3] #this is what lists look like
y=x #assign reference to the list to y
x.append(4) #manipulate the list by adding a value
print(y) #y also changed, because of assingment by reference

# Lists
Lists are written in square brackets, as you have seen above. Lists can contain values of mixed types. List indices start with 0, as you can see here:

In [ ]:
li = [17,"Hello",4.1,"Bar",5,6]
li[2]

You can also use negative indices, which means that we start counting from the right:

In [ ]:
li[-2]

You can also select subsets of lists ("slicing"), like this:

In [ ]:
li[2:4]

Note that slicing returns a copy of the sub-list.

## Some more list operators
Here are some more operators you might find useful.

In [8]:
# Boolean test whether a value is in a list: the in operator
t = [1,2,3,4]
2 in t 

# Concatenate lists: the + operator
a = [1,2,3,4]
b = [5,6,7]
c = a + b
print(c)

# Repeat a list n times: the * operator
a=[1,2,3]
3*a
print(3*a)

# Append lists
a=[1,2,3]
a.append(4)

# Index of first occurence
a.index(2)

# Number of occurences
a = [1,2,3,2,1,2]
a.count(2)

# Remove first occurence
a.remove(2)

# Revese the list
a.reverse()

# Sort the list
a.sort()

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


## Dictionaries: A mapping type
Dictionaries are known as maps in other languages: They store a mapping between a set of keys and a set of values. Below is an example on how to use dictionaries:

In [ ]:
# Create a new dictionary
d = {'user':'bozo', 'pswd':1234}

# Access the values via a key
d['user']
d['pswd']

# Add key-value pairs
d['id']=17

# List of keys
d.keys()

# List of values
d.values()

# Functions
Functions in Python work as you would expect: Arguments to functions are passed by assignment, that means passed arguments are assigned to local names. Assignments to arguments cannot affect the caller, but changing mutable arguments might. Here is an example of defining and calling a function:


In [ ]:
def myfun(x,y):
    print("The function is executed.")
    y[0]=8 # This changes the list that y points to
    return(y[1]+x)

mylist = [1,2,3]
result=myfun(17,mylist)
print("Function returned: ",result)
print("List is now: ",mylist)

## Optional Arguments
We can define defaults for arguments that do not need to be passed:

In [9]:
def func(a, b, c=10, d=100):
    print(a, b, c, d)
func(1,2)
func(1,2,d=4)

1 2 10 100
1 2 10 4


Some more facts about functions:
* All functions in Python have a return value, functions without a return statement have the special return value None
* There is no function overloading in Python
* Functions can be used as any other data types: They can be arguments to functions, return values of functions, assigned to variables, etc. This means Python is a functional programming language, and we can do many of things you know and love from Haskell, like higher-order functions!

# Control of Flow
We have already seen If-branches above. For- and While-Loops also work exactly as you would expect, Here are just some examples:

In [ ]:
x = 3
while x < 10:
    if x > 7:
        x += 2
        continue
    x = x + 1
    print("Still in the loop.")
    if x == 8:
        break
print("Outside of the loop.")

In [ ]:
for x in range(10):
    if x > 7:
        x += 2
        continue
    x = x + 1
    print("Still in the loop.")
    if x == 8:
        break
print("Outside of the loop.")

In [13]:
[x for x in [2,3,4]]

[2, 3, 4]

Exercise: Implement a function that tests whether a given number is prime.

In [15]:
def isPrime(n):
    for i in range(2,n):
        if n%i == 0:
            return False
    return True
isPrime(17)

True

# List Comprehensions, 
There is a special syntax for list comprehensions (which you might know from Haskell).

In [ ]:
# List of all multiples of 3 that are <100:
evens = [x for x in range(3,100) if x%3==0]
print(evens)

Exercise: Use a list comprehension to make a list of all primes < 1000.

In [6]:
[x for x in range(2,1000) if isPrime(x)]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887,
 907,
 911,
 919,
 929,
 937,
 941,
 947,
 953,
 967,
 971,
 977,
 983,
 991,
 997]

# Numpy
Numpy is a very popular Python package that allows to work more easily with numeric arrays. It is the basis for much of what you will see in this course.

## Importing Modules/Packages

In order to work with numeric arrays, we import the [NumPy](http://www.numpy.org) package.

In [ ]:
import numpy as np

Now we can use all NumPy functions (by prefixing "`np.`").

In [18]:
np.zeros(10000)

array([0., 0., 0., ..., 0., 0., 0.])

## Tab Completion

*Exercise:* Type "`np.ze`" (without the quotes) and then hit the *Tab* key ...

In [19]:
np.zeros?

## Array, Vector, Matrix

Arrays can have arbitrarily many dimensions, but let's use only one-dimensional arrays for now.
Arrays can be created with [numpy.array()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html):

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Note that the result is not displayed when you assign to a variable (because assignment is a *statement* and not an *expression*).
To show the data, write the variable name separately as the last (or only) line of a code cell.

In [ ]:
a

BTW, there is an easier way to get this particular array (using [numpy.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)):

In [20]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Getting Help

If you want to know details about the usage of `np.arange()` and all its supported arguments, have a look at its help text.
Just append a question mark to the function name (without parentheses!):

In [ ]:
np.arange?

A help window should open in the lower part of the browser window.
This window can be closed by hitting the *q* key (like "quit").

Let's get some more help:

In [ ]:
np.zeros?

You can also get help for the whole NumPy package:

In [ ]:
np?

You can get help for any object by appending (or prepending) a question mark to the name of the object.
Let's check what the help system can tell us about our variable `a`:

In [ ]:
a?

The help system may come in handy when solving the following exercises ...

## `np.arange()`

We'll often need sequences of evenly spaced numbers, so let's create some.

*Exercise:* Create a sequence of numbers with `np.arange()`, starting with 0 and up to (but not including) 6 with a step size of 1.

In [21]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

*Exercise:* Create a sequence of numbers with `np.arange()`, starting with 0 and up to (but not including) 0.6 with a step size of 0.1.

In [22]:
np.arange(0,0.6,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

*Exercise:* Create a sequence of numbers with `np.arange()`, starting with 0.5 and up to (but not including) 1.1 with a step size of 0.1.

In [24]:
np.arange(0.5,1.1,0.1)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

The previous exercise is somewhat tricky.
If you got it right, have a look at [arange considered harmful](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/misc/arange.ipynb) for what you *could have* done wrong.
If you got an unexpected result, have a look at [arange considered harmful](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/misc/arange.ipynb) for an explanation.

*Exercise:* Can you fix the problem?

What do we learn from all this?
$\Rightarrow$
`np.arange()` is great, but use it only with integer step sizes!

## `np.linspace()`

Another, slightly different method to create a sequence of evenly spaced numbers is [numpy.linspace()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html).
Have a look at the documentation.

In [ ]:
np.linspace?

*Exercise:* Create a sequence of numbers with `np.linspace()`, starting with 0 and up to (including) 6 with a step size of 1.

In [31]:
a = (6.0-0.0+1)/1.0
np.linspace(0,6,a)

/opt/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  from ipykernel import kernelapp as app


array([0., 1., 2., 3., 4., 5., 6.])

Note that the resulting array will have a *floating point* data type even if all inputs (and the step size) are integers.
This is not the case with `np.arange()`.

*Exercise:* Create a sequence of numbers with `np.linspace()`, starting with 0 and up to (but not including) 6 with a step size of 1.

*Exercise:* Create a sequence of numbers with `np.linspace()`, starting with 0 and up to (but not including) 0.6 with a step size of 0.1.

*Exercise:* Create a sequence of numbers with `np.linspace()`, starting with 0.5 and up to (but not including) 1.1 with a step size of 0.1.

Note that `np.linspace()` doesn't have the above-mentioned problem we had with `np.arange()`.

## Creating a Sine Wave

Let's create some more interesting array, representing a digital sine signal. The signal will follow the equation $y(t) = A\sin(\omega t)$ with $\omega = 2\pi f$ and $f$ being the frequency of the sine.
The maximum signal amplitude is given by $A$.
The variable $t$ obviously represents time.
Let's create a digital signal with evenly spaced values for $t$.

We can use the function [numpy.sin()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html) to create a sine tone. Let's look at its help text first.

In [ ]:
np.sin?

Now that we know which function to call, we need appropriate input.
And that's where our sequences of evenly spaced values from above come into play.

The nice thing about NumPy functions like `np.sin()` is that they can operate on whole arrays at once, so it is not necessary to call the function on each single value separately.
Therefore, we can store the whole range of values for our time variable $t$ in one array.

According to the equation, each value of $t$ has to be multiplied with (the constant) $\omega$.
That's another nice thing about NumPy: we don't have to multiply every value of the array $t$ separately with $\omega$, we can multiply the whole array with a scalar at once, and NumPy does the element-wise multiplication for us.
This is called ["broadcasting"](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html), in case you stumble upon that word in the docs.
The array returned by `np.sin()` can (again using broadcasting) be multiplied by the constant scalar $A$ to get the final result.

The only thing that's still missing is $\pi$, but that's simple:

In [ ]:
np.pi

Now, let us create a sine wave with a frequency of 2 Hz, a duration of 1 second and an amplitude of 0.3.
We use a sampling rate of 44.1 kHz.

In [ ]:
dur = 1  # duration in seconds
amp = 0.3  # maximum amplitude
freq = 2  # frequency of the sine tone in Hertz
fs = 44100  # sampling frequency in Hertz

t = np.arange(np.ceil(dur * fs)) / fs
y = amp * np.sin(2 * np.pi * freq * t)

*Exercise:* Use the [built-in len() function](https://docs.python.org/3/library/functions.html#len) to find out how many samples the resulting signal has.
How many is it supposed to have?

## Plotting

Python and NumPy cannot plot by themselves, they need some help from [matplotlib](http://matplotlib.org/).

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

Now we can plot the data from our array:

In [ ]:
plt.plot(y)

As always, for more info:

In [ ]:
%matplotlib?

## Tweaking the Plot

Let's look again at our plot.

In [ ]:
plt.plot(y);

Since we passed only a single array to the `plot()` function, the x-axis shows the sample index from 0 to the length of the signal in samples (minus one).
It may be more meaningful to show the time in seconds.

But let's close the previous plot first.

In [ ]:
plt.close()

If we pass two arrays to the `plot()` function, the first one defines the mapping from sample indices to the actual values displayed on the x-axis, the second one specifies the corresponding y values.

In [ ]:
plt.plot(t, y);

Good, now the x-axis shows the time in seconds.
Let's create axis labels so that everyone knows.

In [ ]:
plt.plot(t, y)
plt.xlabel("Time / Seconds")
plt.ylabel("Amplitude")
plt.title("Sine Tone with {} Hz".format(freq));

For more information, have a look at [Getting Started With `matplotlib`](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/plotting/matplotlib.ipynb).

## Two-Dimensional Arrays

Two-dimensional arrays somewhat look like lists of lists, but internally, they are still stored in one contiguous area of memory.

There are several functions for creating arrays which allow to specify the number of rows and columns, e.g. [numpy.zeros()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html) and [numpy.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html).

In [ ]:
np.zeros((4, 2))

In [ ]:
np.ones((4, 2))

Arrays can also be created from lists of lists (a.k.a. *nested* lists) with [numpy.array()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html):

In [ ]:
np.array([[.1, .2], [.3, .4], [.5, .6], [.7, .8]])

Note that the inner lists provide the individual rows of the array.

Two-dimensional arrays can also be created by concatenating a list of one-dimensional arrays (or lists) by columns using [numpy.column_stack()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.column_stack.html):

In [ ]:
a = np.column_stack([[.1, .2, .3, .4], [.5, .6, .7, .8]])
a

If you want to flip rows and columns, you can transpose the array:

In [ ]:
b = a.T
b

The transposed array is *not* a copy of the original one, it's rather a different *view* into the same memory.
This means that if you change an element of the transposed array, this change will also be visible in the original array!

In [ ]:
b[1, 2] = 0
a

## Array Properties

Let's create some two-dimensional array:

In [ ]:
x = np.random.normal(scale=0.2, size=(int(1.5 * fs), 2))
x

*Exercise:* Try those different ways to obtain the size of the array:

In [ ]:
len(x)

In [ ]:
x.shape

In [ ]:
x.size

In [ ]:
x.nbytes

*Exercise:* There's much more information about the array, try the following commands and find out what they mean.

In [ ]:
x.ndim

In [ ]:
x.dtype

In [ ]:
x.itemsize

In [ ]:
x.strides

In [ ]:
x.flags

*Exercise:*
You can also get some statistical values about the data in the array.
Check if they are consistent with the given normally distributed noise signal.

In [ ]:
x.max()

In [ ]:
x.min()

In [ ]:
x.ptp()

In [ ]:
x.mean()

In [ ]:
x.std()

In [ ]:
x.var()

Most of these *methods* also exist as *functions*, e.g.

In [ ]:
np.max(x)

Both the functions and the methods have an optional *axis* argument.

*Exercise:* Try `axis=0` with all of the above functions/methods.

In [ ]:
x.std(axis=0)

In [ ]:
np.mean(x, axis=0)

*Exercise:* What's the difference between `axis=0` and `axis=1`?
What does `axis=-1` mean?

## Broadcasting

We already saw before, that when a scalar is multiplied by an array, this multiplication is done element-wise on the array.
The NumPy people call this [broadcasting](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

The great thing about it is that it is not limited to operations between a scalar and an array, but also between arrays of different numbers of dimensions.

Let's, for example, take a one-dimensional array with two values and multiply it with our two-dimensional array `x` from before:

In [ ]:
np.array([0.5, 100]) * x

Although these two arrays clearly have a different shape and a different number of dimensions, the multiplication worked.
In this case, each element of the first column of `x` was multiplied with the first value of the other array, and same for the second column and the second value of the array.

In this example, the result has the same shape of one of the operands, and the other operand was "stretched" along its singular (or rather missing) dimension.

But it doesn't have to be that way.
Let's create a two-dimensional array that consists of only one column:

In [ ]:
y = np.random.normal(scale=0.2, size=(int(1.5 * fs), 1))
y

In [ ]:
y.shape

When we multiply a one-dimensional array with this two-dimensional column-array, none of the dimensions have the same size.
Nevertheless, we can multiply them and both arrays get "stretched" (along their singular/missing dimension) leading to a result having a shape larger than any of the operands:

In [ ]:
np.array([0.5, 100]) * y

The left column of the result is `y` multiplied by the first element of the one-dimensional array, the right column is the same `y` multiplied by the second element.

<p xmlns:dct="http://purl.org/dc/terms/">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <span rel="dct:publisher" resource="[_:publisher]">the person who associated CC0</span>
  with this work has waived all copyright and related or neighboring
  rights to this work.
</p>